### ISSUE TITLE
Add set/get for URL and Citation

### ISSUE THREAD

**Issue by empavia** [natcap/geometamaker#17]
Add features to set and get the:

- URL to the dataset. This will be a URL to Google Drive or Cloud (or elsewhere) to point CKAN to where the file associated with the MCF is located. Found in identification.url OR distribution.url
- Citation. There is not a specific place for this in the MCF. We can think about whether we can create an attribute section for this, or whether we want to add it the abstract or lineage, etc.

**Comment by davemfish** [comment]
> * Citation. There is not a specific place for this in the MCF. We can think about whether we can create an attribute section for this, or whether we want to add it the abstract or lineage, etc.

I think it makes sense to add a `citation` property to the `identification` section of the MCF. That section has properties like `title, abstract, edition, doi`, so it seems fitting there.

**Comment by empavia** [comment]
> > * Citation. There is not a specific place for this in the MCF. We can think about whether we can create an attribute section for this, or whether we want to add it the abstract or lineage, etc.
> 
> I think it makes sense to add a `citation` property to the `identification` section of the MCF. That section has properties like `title, abstract, edition, doi`, so it seems fitting there.

This makes sense to me! I am good with that.
