### ISSUE TITLE
Allow multiple ways to define a CRS

### ISSUE THREAD

**Issue by phargogh** [natcap/geometamaker#34]
As it stands, `geometamaker`'s `crs` attribute describes the WKT spatial reference system.  But there are a number of ways to define a spatial reference system, and (I believe) not all spatial reference systems are able to describe each other.

My request is to be able to specify the standard of the spatial reference system in addition to the CRS itself so that we can easily handle a variety of different CRS's, but also so that we can add any CRS's that make sense to add in the future.

**Comment by davemfish** [comment]
@phargogh clearly defining the standard ('wkt') represented by the string would be an improvement:

```
spatial:
    bounding_box: ...
    crs:
        wkt: 'PROJCS["NAD83 / UTM zone 10N",...AUTHORITY["EPSG","26910"]]'
```

As it stands, this `spatial` section and it's children do not have public setters. `geometamaker` initializes them, but we don't intend users to modify them because we don't want them to become out of sync with the dataset. Are you hoping that we open up this up and allow a user to add another representation of the CRS besides WKT? Or would it be useful to have `geometamaker` add more by default?

**Comment by phargogh** [comment]
Well, in my original request, I had forgotten that the WKT would be populated by geometamaker and not by the user.  And so I was thinking that it might be nice to allow the SRS format to be defined along with the SRS itself.  For example:
```
crs: "wkt:PROJCS..."
crs: "EPSG:4326"
crs: "ESRI:102060"
crs: "proj:<some proj string>"
```

I agree with you though that since the SRS information is pulled directly from the dataset, the approach we take should be one that is relatively straightforward to compute.  And I also think that this information should continue to be done automatically, without any user overrides.  If someone knows better than GDAL what the SRS should be, then it'd make sense for them to edit that manually.

Having said all of that, I think the real thing my feature request was trying to get at was that it'd be great to use a shorthand to describe the SRS instead of the full WKT string in order to keep the YML more readable where possible.  So `EPSG:4326` instead of the full WKT string.  I don't know if it'd work for `ESRI:____` codes, but this might work for EPSG codes?

```python
ds = gdal.OpenEx(raster_path)
srs = osr.SpatialReference(ds.GetProjection())
srs.AutoIdentifyEPSG()
print(f"{srs.GetAttrValue('AUTHORITY', 0)}:{srs.GetAttrValue('AUTHORITY', 1)}")
```

Anyways, just a thought!
